### ISSUE TITLE
[IBEX] Code Review: IBEX integration with galoy backend using USD wallet to receive lightning via LN Invoice - Bounty #3

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash#10]
This task is to do a comprehensive code review for the changes made to the flash backend that replace the galoy USD (stablesats) wallet with the IBEX custodial USD wallet when generating a lightning invoice using the `LnUsdInvoiceCreate` mutation, **and** suggest a solution for updating the flash backend with the updated IBEX wallet balance once the invoice has been paid and the IBEX API returns the webhook.

The branch with these changes [can be found here](https://github.com/lnflash/flash/tree/ln-usd-ibex-invoice)
Submitted PR [can be found here](https://github.com/lnflash/flash/pull/12)

For testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql
For testing the IBEX API you can connect to http://api-development.flashapp.me:8760/api/v1/

BOUNTY available ⚡⚡⚡

**Comment by ecurrencyhodler** [comment]
Bounty [posted!](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696812136)
