### ISSUE TITLE
[IBEX] Complete IBEX integration with galoy backend using USD wallet to send lightning via LN Invoice - Bounty #5

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash#11]
This task is to replace the galoy USD (stablesats) wallet with the IBEX custodial USD wallet when paying a lightning invoice using the LnNoAmountUsdInvoicePaymentSend mutation ( and any other related mutations) and update the flash backend persistent storage with the updated IBEX wallet balance once the invoice has been paid and the IBEX API returns the webhook.

For reference on how I did the changes to the LnUsdInvoiceCreate Mutation [please see here (https://github.com/lnflash/flash/tree/ln-usd-ibex-invoice) 
Code improvement suggestions are welcome.

For testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql
For testing the IBEX API you can connect to http://api-development.flashapp.me:8760/api/v1/

BOUNTY available ⚡⚡⚡

**Comment by ecurrencyhodler** [comment]
Bounty [posted!](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696811998)
