### ISSUE TITLE
[IBEX] IBEX integration with galoy backend using USD wallet to display IBEX wallet balance - Bounty #4

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash#13]
This task is to replace the galoy USD (stablesats) wallet with the IBEX custodial USD wallet on the Home Screen in the `wallet overview` component on the frontend, so that it is displaying the latest balance of the IBEX custodial USD wallet.

The stablesats wallet uses a graphql query to get the latest balance from galoy, so ideally this would also use a graphql query to get the latest balance from flash backend. This means the flash backend could be storing the balance, and use the IBEX API to get the latest balance if the balance is stale.

An alternate solution would be to hit the IBEX API every time we need a balance, instead of storing the balance on the server.

Code improvements and suggestions are welcome.

For testing the frontend you can connect the staging environment to http://api-development.flashapp.me:4002/graphql
For testing the IBEX API you can connect to http://api-development.flashapp.me:8760/api/v1/

BOUNTY available ⚡⚡⚡

**Comment by ecurrencyhodler** [comment]
Bounty [posted!](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696812382)
