### ISSUE TITLE
LN Fee Estimation

### ISSUE THREAD

**Issue by brh28** [lnflash/flash#22]
UI: "Failed to calculate fee." 

See: https://github.com/lnflash/flash/pull/17#issuecomment-1880423797

Backend: 

- lnNoAmountInvoiceFeeProbe: graphQL error
- lnInvoiceFeeProbe: tested successfully

**Comment by brh28** [comment]
Following up on this item as we've addressed fee estimation for USD invoices that have amounts. Are these NoAmountInvoices relevant? @Nodirbek75

**Comment by Nodirbek75** [comment]
I'm getting this error message for no amount invoices:
`[GraphQL error]: Message: Cannot read properties of undefined (reading 'data'), Path: lnNoAmountUsdInvoiceFeeProbe} {"locations": [{"column": 93, "line": 1}]}`
![Simulator Screenshot - iPhone 11 Pro Max - 2024-08-28 at 22 52 45](https://github.com/user-attachments/assets/4e2f5b8b-05f3-429c-9f85-3f49016e0809)

**Comment by brh28** [comment]
Do you know why we're calling the `lnNoAmountUsdInvoiceFeeProbe` mutation when an amount is available?

**Comment by brh28** [comment]
Fix: https://github.com/lnflash/flash/pull/98
