### ISSUE TITLE
Email authentication

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/flash#34]
When trying to add an email to an account, no email is being sent to the user.

**Comment by brh28** [comment]
@Nodirbek75 @islandbitcoin Can either of you provide a sample query along with any other relevant information?

**Comment by Nodirbek75** [comment]
@brh28 
Endpoint: `/auth/email/code`
Data: `data: {
               email: emailInput
            }`

**Comment by brh28** [comment]
## Issue

#### Description of problem

For my current user (brh28), I do not see my email as a login method from the UI, but when I attempt to add my email, I get an error with message "Email is already attached to account.". When viewing [the trace](https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/staging-api/result/DfZWc4zdzBn/trace/9A3NHgc7VKF?fields[]=s_name&fields[]=s_serviceName&span=827b90d00220d900), we see error type of`AccountAlreadyHasEmailError`. MongoDB does not show a record of the email in users or accounts, but Kratos admin identity api does show the email. 

So it seems we're in a partial state where kratos is recording a new email, but it's not being added to our mongo db.

#### Reproduction steps

I'm not sure how to reproduce, but my guess is this is the typical path when trying to add an email.

#### Actions

May need to be moved to a separate issue, but leaving here for now for documentation purposes

**Comment by brh28** [comment]
Triggered an email code confirmation using import wallet flow. Sample trace viewable [here](https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/staging-api/trace/GPb1W4xABHx?fields[]=s_name&fields[]=s_serviceName&span=e517c270c57d1c87). Trace shows successful call to trigger an email to the url: http://flash-kratos-public/self-service/recovery?flow=f379a5b7-1465-4afa-942a-15dd304e199b

Looking at kratos pod logs: 
```
{"address":"benhindman@gmail.com","audience":"application","level":"debug","msg":"Preparing recovery code.","service_name":"Ory Kratos","service_version":"v1.0.0","time":"2024-07-28T17:37:38.573771915Z","via":"email"}
{"audience":"audit","email_address":"benhindman@gmail.com","identity_id":"fd238f35-2539-4b2f-8a3d-7b8b7022c6ab","level":"info","msg":"Sending out recovery email with recovery code.","recovery_code":"041921","recovery_code_id":"28b8b0e9-5a22-4e16-bca0-055e7c3e91c3","service_name":"Ory Kratos","service_version":"v1.0.0","time":"2024-07-28T17:37:38.592140974Z","via":"email"}
```

**Comment by brh28** [comment]
@islandbitcoin is setting up smtp server

**Comment by brh28** [comment]
SMTP server is set up and configured from staging. 

I was able to successfully test an email using the "Import Wallet" flow. However, adding an email to an existing account is giving the same `AccountAlreadyHasEmailError` error as described [above](https://github.com/lnflash/flash/issues/34#issuecomment-2254587211).

**Comment by brh28** [comment]
Upon testing in our newly set-up test environment:

- ben@wordform.space is not considered a valid email. @nodirbek75 I'm wondering what our rules are and why this is being rejected
- New email template looks better, but getting an error from my email client: 
```
This email has failed its domain's authentication requirements. It may be spoofed or improperly forwarded. Learn more
```
I'll look into this.
- Tested adding an email to existing account - Success.
- Tested logging into account using email - Success

However, on the settings screen, my email does not display as under Login Methods. @Nodirbek75 can you let me know where this data is being queried from?

**Comment by islandbitcoin** [comment]
tested on test environment, got the confirmation email sent to junk folder.
seems to have been added successfully, but cannot see it on the settings page.
logged in with email successfully

**Comment by islandbitcoin** [comment]
This PR should fix the display issue: https://github.com/lnflash/flash-mobile/pull/224

**Comment by brh28** [comment]
@islandbitcoin to look into domain authentication requirements

**Comment by brh28** [comment]
Domain authentication error resolved. @islandbitcoin are we good to close this?

**Comment by islandbitcoin** [comment]
Yes. Closing as resolved.
