### ISSUE TITLE
Disable AppCheck

### ISSUE THREAD

**Issue by brh28** [lnflash/flash#38]
We want to install/download APK and disable appcheck so app runs without google/apple

**Comment by brh28** [comment]
Check is part of the `/auth/create/device-account` request. 

@Nodirbek75 If you let me know the failing response of this endpoint, I'll better be able to trace where the check is occurring on the backend.

**Comment by islandbitcoin** [comment]
@brh28 Can we close this issue?

**Comment by brh28** [comment]
To my knowledge yes, but I don't think we ever made changes here.
