### ISSUE TITLE
Add a way to setup locally without the ibex password

### ISSUE THREAD

**Issue by abhay-raizada** [lnflash/flash#40]
Right now the app requires the ibex password to be able to setup, it would be nice to be able to setup locally without it

**Comment by brh28** [comment]
Not sure this is possibly without running an ibex server locally because we'll need some form of client authentication to use the staging API

**Comment by brh28** [comment]
Pointing the local dev environment to Ibex is the lowest friction startup we'll find. Unless we're willing to add credentials to the source code (i.e a public Ibex account), I'd recommend we look into streamlining the on-boarding process for new devs. Ideally, we create a new sandbox account from Ibex directly. This requires understanding Ibex on-boarding flow, but for sandbox, should be relatively simple (perhaps just an API call)    

I'm going to close this as I don't believe there's any action items on it
