### ISSUE TITLE
Create ibex account for staging and work with Ibex to onboarding developer accounts 

### ISSUE THREAD

**Issue by brh28** [lnflash/flash#54]
Follow up of https://github.com/lnflash/flash/issues/40 which was originally motivated for onboarding developers without requiring sharing of ibex password. Adding developer accounts will improve the development experience as more developers (& environments) are run.

Additionally, now that we have a staging env set up, we're using the same Ibex account for multiple environments: staging + each development environment. Each of these environments compete with each other over gaining valid access tokens to Ibex. With minimal developers, this issue is less noticeable. As we add more developers, more environments will be running concurrently which will cause more sign-in flows and risks getting the account locked.

**Comment by brh28** [comment]
Introduction of Ibex otel will gives us insight into the number of times Ibex.signIn is called, which will help us evaluate the priority of this issue

**Comment by islandbitcoin** [comment]
I'm closing this issue since we now have a staging environment and a production environment.
