### ISSUE TITLE
Change the Intraledger API call to an IBEX API call when sending funds to internal users by entering only the username.

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash#71]

**Comment by brh28** [comment]
@Nodirbek75 Can you provide a sample query that's failing from the UI?

**Comment by brh28** [comment]
I assume this is the mutation we're interested in: `intraLedgerUsdPaymentSend`

Looking at the schema, it appears Galoy may be using this mutation for USD -> BTC swaps (and `intraLedgerPaymentSend` for BTC -> USD swaps). @Nodirbek75 what endpoint are we currently using for swaps?

**Comment by brh28** [comment]
Sample trace: https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/galoy-dev-api/result/AwXRiMVUH3w/trace/HSbty2XRuxs?fields[]=s_name&fields[]=s_serviceName&span=3fb774fb834f48f1

**Comment by brh28** [comment]
started a thread in the flash-ibex slack channel for recommended approach to send between Ibex users: https://flash-qwj9494.slack.com/archives/C04K5NC9D3N/p1720568417711049

**Comment by brh28** [comment]
Changed has been deployed to staging. @Nodirbek75 let us know if it functions as expected

**Comment by Nodirbek75** [comment]
@brh28  I'm getting below error message. @islandbitcoin was it working for you?
![Screenshot_1721220326](https://github.com/user-attachments/assets/516e4d9f-eb5a-4bd7-a1ec-5adae539b4bf)

**Comment by islandbitcoin** [comment]
it works for me sending the @Nodirbek75 using nicktest.
I'm sending from the islandbitcoin username.

**Comment by brh28** [comment]
I see the trace, but unfortunately I don't see a stack trace: https://ui.honeycomb.io/island-bitcoin/environments/test/datasets/staging-api/result/n3xTARQJZaT/trace/v3aezeZLkUe?fields[]=s_name&fields[]=s_serviceName&span=57a318b6b30cc367

**Comment by brh28** [comment]
The issue comes from this function: https://github.com/lnflash/flash/blob/e9794ae3c3497b8db575c48307db13b33dfd1a2a/src/app/accounts/index.ts#L43

but still need to figure out why.

@Nodirbek75 Couple questions:
1. When does this error occur? Does it occur for every internal recipient? Does it happen when sending to external lightning address or invoice?
2. Do you know how we can reproduce this issue from another account?
