### ISSUE TITLE
Use DigitalOcean uptime monitoring for production deployment

### ISSUE THREAD

**Issue by brh28** [lnflash/flash#72]
We want to monitor our production deployment for any application downtime. Purpose of this task is to use the DigitalOcean uptime monitoring tooling to do health checks on hosted infrastructure: 

- [x] Graphql API
- [x] Ibex Webhook

Read more here: https://www.digitalocean.com/products/uptime-monitoring

**Comment by brh28** [comment]
Graphql /healthz endpoint is behind Oathkeeper. This PR makes it publically accessible, so that DigitalOcean can make requests to it: https://github.com/lnflash/charts/pull/48

**Comment by brh28** [comment]
Added Digital Ocean uptime monitoring for Graphql api and Ibex Webhook as well as uptime alerts to the emails bhindman@proton.me & github@bobodread.com.

https://cloud.digitalocean.com/monitors/uptime/checks/?i=d65ac8

**Comment by islandbitcoin** [comment]
DigitalOcean seems to provide an API to publicly display the uptime info:

```
curl -X GET -H "Content-Type: application/json" \
     -H "Authorization: Bearer your_api_token" \
     "https://api.digitalocean.com/v2/uptime_checks"
```
