### ISSUE TITLE
Send push notification to the user when using LNURLp

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash#74]
deviceToken being saved using below mutation: 

`mutation deviceNotificationTokenCreate($input: DeviceNotificationTokenCreateInput!) {
    deviceNotificationTokenCreate(input: $input) {
      errors {
        message
      }
      success
    }
  }`

**Comment by Nodirbek75** [comment]
Notification types:

- [ ] Ibex USD Payment receive
- [ ] Breez BTC Payment receive
- [ ] Ibex USD Onchain confirm
- [ ] Breez BTC Onchain confirm
- [ ] Price change
- [ ] Marketing notification

**Comment by brh28** [comment]
Closing this as we LNURLp notifications are working. For other notification types, let's use https://github.com/lnflash/flash-mobile/issues/172
