### ISSUE TITLE
Wrong fee calculation when sending from ibex USD wallet

### ISSUE THREAD

**Issue by Nodirbek75** [lnflash/flash#78]
Calling this mutation to get the fee:
```
mutation lnUsdInvoiceFeeProbe($input: LnUsdInvoiceFeeProbeInput!) {
    lnUsdInvoiceFeeProbe(input: $input) {
      errors {
        message
      }
      amount
   }
}
```
  
![Screenshot_1721662358](https://github.com/user-attachments/assets/985f287b-060e-4cc9-855c-337b23b244bf)

**Comment by brh28** [comment]
Deployed to prod. So far, testing looks good. I've seen fee estimations of $0.00 and $0.01 which both matched the actual fee.

If any issues arise, we can reopen or create a new issue
